### PR TITLE
Add xrt_deconvolve

### PR DESCRIPTION
**Pull request by jslavin**
xrt_deconvolve uses the Hinode XRT point spread function and the Richardson-Lucy algorithm to deconvolve (sharpen) an XRT image. A test and notebook are included.

### CODE REVIEW

**Comment by joyvelasquez** [comment]
> joyvelasquez

**Comment by joyvelasquez** [comment]
>

**Comment by joyvelasquez** [comment]
I agree with you @jslavin, lets move to /util.

**Comment by jslavin** [comment]
So this is failing on Windows beacuse a test of xrt_deconvolve for the case where chip_sum = 2. In that case the PSF needs to be rebinned to match the resolution of the image. I do that via a call to affine_transform in SunPy which in turn imports scikit-image. Apparently scikit-image is not a requirement yet for xrtpy. Can we add that? I'm a bit surpised that it's not a requirement since it seems that it is for SunPy.

**Comment by joyvelasquez** [comment]
Nice find @jslavin !
@namurphy , as Jon asked, how do we feel about "scikit-image"  being a requirement for xrtpy?

**Comment by namurphy** [comment]
I'm happy for `scikit-image` to be a package requirement.  We'd need to add it under `requirements/install.txt` and then under `install_requires` in `setup.cfg`.

**Pull request merged**
