### PR TITLE
Updating xrt contam on ccd file Nov 2024

### PR DESCRIPTION
**Pull request by joyvelasquez**
This pull request updates the xrt_contam_on_ccd.geny file in the XRTpy repository. The file is maintained monthly to ensure the accuracy and reliability of calculations, such as the effective area and temperature response.
File Last Updated: 2024-11-20, 07:14

### CODE REVIEW

**Comment by joyvelasquez** [comment]
pre-commit.ci autofix

**Comment by nabobalis** [comment]
How are these files updated?

**Comment by joyvelasquez** [comment]
Hi @nabobalis,

Currently, the updates are done manually on a monthly basis from this link: https://hesperia.gsfc.nasa.gov/ssw/hinode/xrt/idl/response/contam/.

I’m planning to automate this step to streamline the process. Let me know if you have any input or suggestions!

**Comment by joyvelasquez** [comment]
Made edits directly to the main branch on the github web interface due to on solvable issues on my local machine.

**Pull request closed without merging**
